### ISSUE TITLE
Reading file from the network? Example code.

### ISSUE THREAD

**Issue by spelufo** [tlnagy/TiffImages.jl#103]
Hi, I wanted to load an image from an HTTP server without saving it to disk and came up with this snippet. I don't know if this is a supported usage or if it is wrong in some way / has some downside. I sort of matched the type signatures until I found a combination that worked. If it is good, maybe it could be added to the examples.

```julia
function load_tiff_without_saving(url)
  buffer = IOBuffer()
  Downloads.download(url, buffer)
  bufstream = TiffImages.getstream(format"TIFF", buffer)
  TiffImages.load(read(bufstream, TiffFile))
end
```

**Comment by tlnagy** [comment]
Yeah, I think it might be nice to have small examples of common patterns in the docs. Might be nice to add a another Literate doc under "Examples" called "Common Patterns" and have small little vignettes under that?

Could be a good usage of https://github.com/JuliaDocs/DemoCards.jl to handle such small vignettes.

**Comment by tlnagy** [comment]
Thanks @spelufo! I added your code to a small demo in #112.
