### ISSUE TITLE
DEFLATE decoding is allocation-intensive

### ISSUE THREAD

**Issue by chrstphrbrns** [tlnagy/TiffImages.jl#115]
As one can see, the allocations are way out of proportion to the file size
```julia
julia> using TiffImages

julia> @time TiffImages.load("/home/chris/red_deflate.tif");
  1.064223 seconds (2.22 M allocations: 267.701 MiB, 8.74% gc time, 76.13% compilation time)

julia> @time TiffImages.load("/home/chris/red_deflate.tif");
  0.272420 seconds (1.01 M allocations: 183.330 MiB, 16.64% gc time)

(@v1.11) pkg> status TiffImages
Status `~/.julia/environments/v1.11/Project.toml`
  [731e570b] TiffImages v0.6.6
```
```bash
> ls -lh /home/chris/red_deflate.tif
-rw-rw-r-- 1 chris chris 89K Sep 26 07:10 /home/chris/red_deflate.tif
> file /home/chris/red_deflate.tif
/home/chris/red_deflate.tif: TIFF image data, little-endian, direntries=23, height=720, bps=19146, compression=deflate, PhotometricIntepretation=RGB, orientation=upper-left, width=1280
```

**Comment by tlnagy** [comment]
Huh. Our DEFLATE implementation is quite simple on the `TiffImages` side, [we just call out](https://github.com/tlnagy/TiffImages.jl/blob/cd7c728800d94e00cb983926957874d7fd23bfb2/src/compression.jl#L31-L37) to @GunnarFarneback's `Inflate.jl` library. Do you mind some basic allocation profiling (see https://docs.julialang.org/en/v1/manual/performance-tips/#tools) and let us know what the culprit is?

**Comment by timholy** [comment]
Does the image have ~1M pixels? That might be 1 or 2 allocations per pixel. Should be easy to find with `@profile` and `ProfileView` if it's due to type-instability.

**Comment by GunnarFarneback** [comment]
Much of the Inflate code goes back ten years and it has never been optimized for allocations, so I don't doubt that there is room for improvement. At the same time I would be rather surprised if there's any significant amount of type instability.

**Comment by chrstphrbrns** [comment]
[This](https://github.com/GunnarFarneback/Inflate.jl/blob/8bae86f946c05744145c5fcb50f20178f054f84e/src/Inflate.jl#L765C5-L765C5) line seems to be the culprit

**Comment by GunnarFarneback** [comment]
Looks like [aliasing detection](https://github.com/GunnarFarneback/Inflate.jl/pull/11) strikes back. Better open an issue in the Inflate repo.

**Comment by GunnarFarneback** [comment]
Please check whether PR #121 solves this problem.
