### ISSUE TITLE
Files with inconsistent image slice sizes break loading

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/TiffImages.jl#139]
Currently TIFF images with embedded reduced resolution images cause problems since `TiffImages` assumes the images aren't ragged.

Take [DAPI Myog Pax7_CH1.zip](https://github.com/tlnagy/TiffImages.jl/files/13620275/DAPI.Myog.Pax7_CH1.zip) for example, which fails to load:

```julia
julia> TiffImages.load("DAPI Myog Pax7_CH1.tif")
ERROR: EOFError: read end of file
Stacktrace:
  [1] unsafe_read(s::IOStream, p::Ptr{UInt8}, nb::UInt64)
    @ Base ./iostream.jl:428
  [2] unsafe_read
    @ ./io.jl:761 [inlined]
  [3] read!
    @ ./io.jl:779 [inlined]
  [4] read!(file::TiffFile{UInt32, FileIO.Stream{FileIO.DataFormat{:TIFF}, IOStream, String}}, arr::Matrix{ColorTypes.RGB{FixedPointNumbers.N0f8}})
```

However, loading the image planes separately works:

```julia
tf = read(open("DAPI Myog Pax7_CH1.tif"), TiffFile)
ifds = collect(tf)
TiffImages.load!.(Ref(tf), ifds)
size(TiffImages.load(tf, ifds[1:1], nothing))
```
(720, 960)

and 

```julia
size(TiffImages.load(tf, ifds[2:2], nothing))
```
(120, 160).

It appears as though we are handling everything just fine, it's just that we should detect when images are "ragged", i.e. don't have the same XY sizes and load those images as the currently unimplemented [`StridedTaggedImage`](https://github.com/tlnagy/TiffImages.jl/blob/bda25ffe31737a5ab93e6f470ea933aea3961384/src/types/strided.jl#L1-L5)

**Comment by chrstphrbrns** [comment]
I've come across GeoTIFFs with ragged data, so this is a must for 1.0 IMHO

**Comment by chrstphrbrns** [comment]
Thoughts on how to handle `LazyBufferedTIFF`, which assumes slices are homogeneous in size and color type?

**Comment by tlnagy** [comment]
`LazyBufferedTIFF` is currently a subtype of `DenseTIFF` so it should just error and not support ragged TIFFs. We could discuss whether that subtyping is the best, but just erroring could be fine for now.
