### ISSUE TITLE
Tiled image metadata anomaly

### ISSUE THREAD

**Issue by chrstphrbrns** [tlnagy/TiffImages.jl#140]
`quad-tile.tif` in the LibTiff test suite uses `STRIPBYTECOUNTS` and `STRIPOFFSETS` instead of `TILEBYTECOUNTS` and `TILEOFFSETS`, which the current logic is expecting

**Comment by tlnagy** [comment]
Thanks @chrstphrbrns!

(also, that TIFF writers can save tiled images without tileoffset and tilebytecounts is absurd)
