### ISSUE TITLE
Inconsistent loading of big tiffs

### ISSUE THREAD

**Issue by RpfR2000** [tlnagy/TiffImages.jl#150]
Hi,

I've come across another issue related to loading Tiffs (3D in space + time). Sometimes, all slices load in just fine (z and t are combined but that can be fixed easily) but other times only the first XY slice loads. The Tiffs were created the exact same way using ImageJ so it's hard to imagine that there's a discrepancy on that end. Do you know what the problem might be? Or how to figure it out?

Thanks!

**Comment by tlnagy** [comment]
Can you give the output of 

```julia
using TiffImages
img = TiffImages.load("your img.tif")
first(ifds(img)) # prints out the tags in the first image plane
```

for both images that do and don't have that behavior? This is likely going to be trickier to diagnose without more information. If you have minimal tiffs that show both behaviors you can always email them using the email in my Github profile and I can take a look when I get a chance. It's very likely that ImageJ is doing something unexpected behind-the-scences.

**Comment by RpfR2000** [comment]
Thanks for the quick response! This is an example output for images that load correctly: 

Tag(SUBFILETYPE, 0)                                                                                                                                                                                                                                                                     Tag(IMAGEWIDTH, 642)                                                                                                                                                                                                                                                                    Tag(IMAGELENGTH, 528)                                                                                                                                                                                                                                                                   Tag(BITSPERSAMPLE, 16)                                                                                                                                                                                                                                                                  Tag(COMPRESSION, COMPRESSION_NONE)                                                                                                                                                                                                                                                      Tag(PHOTOMETRIC, 1)                                                                                                                                                                                                                                                                     Tag(IMAGEDESCRIPTION, "ImageJ=1.53t                                                                                                                                                                                                                                             images=...")                                                                                                                                                                                                                                                                                    Tag(STRIPOFFSETS, 1489115)                                                                                                                                                                                                                                                              Tag(SAMPLESPERPIXEL, 1)                                                                                                                                                                                                                                                                 Tag(STRIPBYTECOUNTS, 677952)                                                                                                                                                                                                                                                            Tag(XRESOLUTION, 0x000f4240//0x00eac027)                                                                                                                                                                                                                                                Tag(YRESOLUTION, 0x000f4240//0x00eac027)                                                                                                                                                                                                                                                Tag(RESOLUTIONUNIT, 1)                                                                                                                                                                                                                                                                  Tag(COLORMAP, UInt16[0, 0, 256, 512, 768, ...])                                                                                                                                                                                                                                         Tag(SAMPLEFORMAT, 1)                                                                                                                                                                                                                                                                    Tag(IMAGEJ_METADATA_BYTECOUNTS, UInt32[20, 882300, 110, 110, 110, ...])                                                                                                                                                                                                                 Tag(IMAGEJ_METADATA, UInt8[73, 74, 73, 74, 105, ...])

This is an example output for images that load incorrectly:

        Tag(SUBFILETYPE, 0)
        Tag(IMAGEWIDTH, 740)
        Tag(IMAGELENGTH, 594)
        Tag(BITSPERSAMPLE, 16)
        Tag(COMPRESSION, COMPRESSION_NONE)
        Tag(PHOTOMETRIC, 1)
        Tag(IMAGEDESCRIPTION, "ImageJ=1.53t
images=...")
        Tag(STRIPOFFSETS, 1642422)
        Tag(SAMPLESPERPIXEL, 1)
        Tag(STRIPBYTECOUNTS, 879120)
        Tag(XRESOLUTION, 0x000f4240//0x00eac027)
        Tag(YRESOLUTION, 0x000f4240//0x00eac027)
        Tag(RESOLUTIONUNIT, 1)
        Tag(COLORMAP, UInt16[0, 0, 256, 512, 768, ...])
        Tag(SAMPLEFORMAT, 1)
        Tag(IMAGEJ_METADATA_BYTECOUNTS, UInt32[20, 971304, 110, 110, 110, ...])
        Tag(IMAGEJ_METADATA, UInt8[73, 74, 73, 74, 105, ...])

If I expand the IMAGEDESCRIPTION, I get this for the correct load:

"ImageJ=1.53t\nimages=5148\nslices=78\nframes=66\nhyperstack=true\nunit=micron\nfinterval=600.0001831054688\nspacing=0.3\nloop=false\nmin=24.0\nmax=4095.0\n"

and this for the incorrect load:

"ImageJ=1.53t\nimages=5694\nslices=78\nframes=73\nhyperstack=true\nunit=micron\nfinterval=599.9938354492188\nspacing=0.3\nloop=false\nmin=102.0\nmax=4095.0\n"

Yes, I'm happy to send minimal examples if necessary. Just let me know.

**Comment by tlnagy** [comment]
So one thing that stands out is that the image that loads correctly is 642 * 528 * 2 * 5148 = ~ 3.47 GiB, while the one that fails is 740 * 594 * 2 * 5694 = ~ 5 GiB. The TIFF file format requires BigTIFF if you save more than 4 gigabytes. I don't believe ImageJ supports this natively (I think you have to use BioFormats to write them properly). Can you give me the output of 

```
typeof(img)
```

for both file types?

**Comment by RpfR2000** [comment]
Interesting, I had no idea. I think your diagnosis is correct, as the issue only comes up for images greater than 4GB. For the correct load, typeof(img) gives: TiffImages.DenseTaggedImage{Gray{N0f16}, 3, UInt32, Array{Gray{N0f16}, 3}} followed by a 2-tuple with entries being the image and the z/xy aspect ratio I think (not really sure), whereas for the incorrect load it just gives: TiffImages.DenseTaggedImage{Gray{N0f16}, 2, UInt32, Matrix{Gray{N0f16}}}

**Comment by tlnagy** [comment]
Yeah, that's the problem. Looks like ImageJ is still labeling the 4+ GB image as a normal TIFF (you can tell because of the UInt32 in the type signature) instead of a BigTIFF which should have a UInt64. That tells me that this is an ImageJ problem. I would try to use the BioFormats plugin in ImageJ which supports images larger than 4 GB.
