### ISSUE TITLE
Is it possible to save grayscale images of type float32?

### ISSUE THREAD

**Issue by RpfR2000** [tlnagy/TiffImages.jl#176]
In the documentation, I only see how to save float images as color images, not grayscale.

Thanks!

**Comment by tlnagy** [comment]
Yes you can, for example:

```julia
julia> using Colors, TiffImages

julia> TiffImages.save("test.tif", rand(Gray{Float32}, 100, 100))
```

**Comment by tlnagy** [comment]
Also, happy to accept PRs to improve the docs if you thought they were unclear.
