### ISSUE TITLE
Decompress after reading in blocks

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/TiffImages.jl#19]
As identified in #17, a key area of weakness is my strategy for inflating compressed data. Currently, I inflate *while* reading the data, which is likely slower than reading a contiguous block followed by in-memory inflation. Plus, I should consider spinning out (some of) the compression code into separate package for reusability sake.

**Comment by tlnagy** [comment]
> Plus, I should consider spinning out (some of) the compression code into separate package for reusability sake.

The compression code is being moved over to https://github.com/tlnagy/Balloons.jl

**Comment by chrstphrbrns** [comment]
#127 implements chunked input

**Comment by tlnagy** [comment]
Agreed, this issue is mostly superfluous in v0.8.0+
