### ISSUE TITLE
The package also supports GeoTIFF?

### ISSUE THREAD

**Issue by juliohm** [tlnagy/TiffImages.jl#41]
I am asking it because I would like to give it a try in a project. I've been using ArchGDAL.jl for GeoTIFF files.

**Comment by tlnagy** [comment]
This package is meant to support TIFF 6.0 compliant files so GeoTIFF files should work, but I haven't personally tried. Do you have an example image that you could share? 

GeoTIFFs would be loaded similarly to standard TIFFs (as `AbstractArray`s of `Colorant`s) and one could probably write a loader that relies on `TiffImages.jl` and just handles the couple extra processing steps to make sense of the extra tags that define the GeoTiff spec.

**Comment by juliohm** [comment]
I tried with a GeoTIFF image and it failed. I am checking if I can share the data here.

**Comment by tlnagy** [comment]
You could also send it to my email listed on my profile page if that's better.

**Comment by tlnagy** [comment]
Some GeoTIFFs appear to work as expected. I downloaded the [Natural Earth I](http://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-1/) GeoTIFF and loaded it with the latest `TiffImages.jl` master and

```julia
julia> img = TiffImages.load("NE1_LR_LC.tif")
8100×16200 TiffImages.DenseTaggedImage{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2,UInt32,Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}}:

# output hidden

julia> img.ifds
1-element Array{TiffImages.IFD{UInt32},1}:
 IFD, with tags: 
        Tag(SUBFILETYPE, 0)
        Tag(IMAGEWIDTH, 16200)
        Tag(IMAGELENGTH, 8100)
        Tag(BITSPERSAMPLE, UInt16[8, 8, 8])
        Tag(COMPRESSION, COMPRESSION_NONE)
        Tag(PHOTOMETRIC, 2)
        Tag(STRIPOFFSETS, UInt32[18962, 67562, 116162, 164762, 213362, ...])
        Tag(ORIENTATION, 1)
        Tag(SAMPLESPERPIXEL, 3)
        Tag(ROWSPERSTRIP, 1)
        Tag(STRIPBYTECOUNTS, UInt32[48600, 48600, 48600, 48600, 48600, ...])
        Tag(XRESOLUTION, 0x00000048//0x00000001)
        Tag(YRESOLUTION, 0x00000048//0x00000001)
        Tag(PLANARCONFIG, 1)
        Tag(RESOLUTIONUNIT, 2)
        Tag(SOFTWARE, "Adobe Photoshop CC 2...")
        Tag(DATETIME, "2014:10:18 11:51:41")
        Tag(XMLPACKET, UInt8[60, 63, 120, 112, 97, ...])
        Tag(UNKNOWN(33550), Float64[0.02222222222222, 0.02222222222222, 0.0])
        Tag(UNKNOWN(33922), Float64[0.0, 0.0, 0.0, -180.0, 90.0, ...])
        Tag(PHOTOSHOP, UInt8[56, 66, 73, 77, 4, ...])
        Tag(EXIFIFD, 393678964)
        Tag(UNKNOWN(34735), UInt16[1, 1, 0, 7, 1024, ...])
        Tag(UNKNOWN(34736), Float64[298.257223563, 6.378137e6])
        Tag(UNKNOWN(34737), "WGS 84|")
```

The image loaded properly and it has (AFAICT) all the necessary GeoTIFF tags, like 34735, etc. Could you be more specific about the error that you encountered?

**Comment by juliohm** [comment]
Sure I got a confirmation that I can share a small geotiff with you. Will
send via email? Let me know how it is best to contact you.

**Comment by tlnagy** [comment]
Email works great! My address is listed on my github profile.

**Comment by juliohm** [comment]
Sorry for the delay on this @tlnagy , switching between multiple tasks. I will converge at some point and send you the email.

**Comment by juliohm** [comment]
Sent you an email with one example file failing.

**Comment by tlnagy** [comment]
As I mentioned in my email, that file fails to load due to the lack of support for LZW compression (#8). It should be fixed when I finish https://github.com/tlnagy/Balloons.jl/pull/3 and #19. 

AFAICT `TiffImages.jl` supports GeoTIFFs and this issue isn't specific to them, please open a new issue if you run into other problems.

**Comment by juliohm** [comment]
Thank you @tlnagy , it would be nice to have the LZW feature ready. I am looking forward to using the package more and more.

**Comment by tlnagy** [comment]
I'm pretty busy with other things right now. The basics are there in Balloons.jl (for decompression at least). I just haven't had time to hook it up in this package. I'm happy to review a PR, but it's going to be a couple months before I can likely get to it.
