### ISSUE TITLE
12-bit tiff support

### ISSUE THREAD

**Issue by stillyslalom** [tlnagy/TiffImages.jl#58]
I have a 12-bit grayscale camera that outputs TIFF stacks with the following tags:
```
        Tag(IMAGEWIDTH, 1024)
        Tag(IMAGELENGTH, 1024)
        Tag(BITSPERSAMPLE, 12)
        Tag(COMPRESSION, COMPRESSION_NONE)
        Tag(PHOTOMETRIC, 1)
        Tag(STRIPOFFSETS, REMOTE@1573010 UInt32[] len=205)
        Tag(ORIENTATION, 1)
        Tag(SAMPLESPERPIXEL, 1)
        Tag(ROWSPERSTRIP, 5)
        Tag(STRIPBYTECOUNTS, REMOTE@1573830 UInt32[] len=205)
        Tag(PLANARCONFIG, 1)
```
The `rawtype_mapping` dict doesn't have an entry for 12-bit images, so TiffImages throws an error on image load:
```
julia> TiffImages.load("filepath.tiff");
ERROR: KeyError: key (TiffImages.SAMPLEFORMAT_UINT, 0x000c) not found
```
I tried working around this by defining
```
TiffImages.rawtype_mapping[(TiffImages.SAMPLEFORMAT_UINT, 12)] = UInt16
```
which gets me past the previous error, but the data is not correctly aligned, so I now see `ERROR: EOFError: read end of file`.

**Comment by tlnagy** [comment]
Oof, that's tricky. In its current form, I don't think that `TiffImages.jl` is flexible enough to support images that are 12bit on disk. The correct solution is probably to read in the entire strip as UInt8s and then repack them in 12bit chunks into UInt16s and reinterpret them as `FixedPointNumbers.N4f12`s.

Do you mind sharing your image with me? My email is on my github profile page.

**Comment by stillyslalom** [comment]
Let me make a trimmed-down stack of images–the full file is ~500 MB.

**Comment by stillyslalom** [comment]
Sorry this is taking so long - the camera that produced these images belongs to a different lab and is back in their hands.

**Comment by stillyslalom** [comment]
While waiting for 12-bit I/O support via FixedPointNumbers.jl, this package may be useful: https://github.com/JaneliaSciComp/UInt12Arrays.jl

**Comment by mkitti** [comment]
The question is what is the format of the 12-bit integers on disk. In UInt12Arrays.jl, I'm currently assuming a certain packing, but it is possible that other packings are used.

**Comment by tlnagy** [comment]
Hey @mkitti, what packing do you assume? I believe TIFFs packed them densely, such that 3x12bit chunks takes 4bits of space.

**Comment by mkitti** [comment]
Little endian.
* The first 12-bit integer has the 4-highest bits from the 4-lowest bits of the second byte with the 8-lower bits coming from the first byte.
* The second 12-bit integer has 4-lowest bits from the 4-highest bits of the second byte with the 8-highest bits coming from the third byte.

Hamamatsu also refers to this as `MONO_12P`.

```
julia> A = [0x10, 0x32, 0x54, 0x76, 0x98, 0xba]
6-element Vector{UInt8}:
 0x10
 0x32
 0x54
 0x76
 0x98
 0xba

julia> UInt12Array(A)
4-element UInt12Vector{UInt16, Vector{UInt8}}:
 0x0210
 0x0543
 0x0876
 0x0ba9

julia> A = rand(UInt8, 6)
6-element Vector{UInt8}:
 0x92
 0xda
 0x18
 0x40
 0xaa
 0xd2

julia> A12 = UInt12Array(A)
4-element UInt12Vector{UInt16, Vector{UInt8}}:
 0x0a92
 0x018d
 0x0a40
 0x0d2a

julia> Int.(A12)
4-element Vector{Int64}:
 2706
  397
 2624
 3370

julia> bitstring.(A)
6-element Vector{String}:
 "10010010"
 "11011010"
 "00011000"
 "01000000"
 "10101010"
 "11010010"

julia> bitstring.(A12)
4-element Vector{String}:
 "0000101010010010"
 "0000000110001101"
 "0000101001000000"
 "0000110100101010"

```

The real purpose the package is the SIMD based unpacking which can be accessed via the `convert` methods.
https://github.com/JaneliaSciComp/UInt12Arrays.jl/blob/main/src/unpack/unpack_simd_256.jl

```
julia> @time copy(A12) # slow conversion of entire array to UInt16
  8.188528 seconds (2 allocations: 4.000 GiB, 3.24% gc time)
2147483648-element Vector{UInt16}:
 0x01c5
 0x0a48
 0x0d6f
...

julia> @time convert(Array{UInt16}, A12) # fast conversion of entire array to UInt16 via SIMD.jl
  1.187842 seconds (4 allocations: 4.000 GiB, 22.17% gc time)
2147483648-element Vector{UInt16}:
 0x01c5
 0x0a48
 0x0d6f
...
```
