### ISSUE TITLE
Can I keep the 3rd dimension with a length of one?

### ISSUE THREAD

**Issue by mdhe1248** [tlnagy/TiffImages.jl#75]
While saving as tiff, is it possible to keep a dimension with a length of one?
The below lose the third dimension after `save`.
```jl
using TiffImages, Images
fn = "3d_img.tif"
img1 = rand(RGB{N0f8}, 10,10,1)
save(fn, img1)
img2 = load(fn)
isequal(img1, img2) # results in `false`
```
On the other hand, the `NRRD` format keeps the dimension.
```jl
fn = "3d_img.nrrd"
save(fn, img1)
img2 = load(fn)
isequal(img1, img2) #results in `true`
```

**Comment by tlnagy** [comment]
On the TIFF side here is no difference on disk between a 3D image with a single plane and a 2D image, currently TiffImages drops the 3rd dimension [here](https://github.com/tlnagy/TiffImages.jl/blob/0bb669af8c53e12fe6da92a4144b8bc955221b2c/src/load.jl#L30) if it is of length 1. You could get the same shape by doing

```julia
julia> img3 = reshape(img2, size(img2)..., 1);

julia> isequal(img1, img3)
true
```

Is that sufficient for your needs?

**Comment by mdhe1248** [comment]
Thank you for pointing out the code. 
Aren't there any difference between 2d and 3d in tiff headers? I don't know much about tiff headers; but just wondering.

**Comment by tlnagy** [comment]
No difference AFAIK. It's basically a linked list on disk with each plane as a node. There's no length encoded in the file.

**Comment by mdhe1248** [comment]
Thanks, I will close this.
