### ISSUE TITLE
Add support for LZW compression

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/TiffImages.jl#8]
LZW compression seems very commonly used with TIFF so it would be nice to support going forward (ref #6).

**Comment by tlnagy** [comment]
Seems like many LZW compressed TIFFs also use horizontal differencing. I need add support for this too.

**Comment by KronosTheLate** [comment]
[This issue (#1017 in Images.jl)](https://github.com/JuliaImages/Images.jl/issues/1017#issuecomment-1593485179), was closed as a dup of this one. I was told to take the discussion over here.

The largest problem, shown in 1017, is the fact that a silent error occurs when loading a LZW compressed tiff image via Images.jl. The image loads, with artifacts introduced. However, TiffImages errors loudly, so the silent error is actually not an issue that I feel belongs in this repo. The silent error part should be fixed ASAP by erring loudly, until someone rolls up their sleeves and adds LZW compression support.
