### ISSUE TITLE
Rename `memmap`?

### ISSUE THREAD

**Issue by timholy** [tlnagy/TiffImages.jl#80]
[`memmap`](https://tamasnagy.com/TiffImages.jl/v0.5.5/lib/public/#TiffImages.memmap) is used for incremental writing. However, as pointed out in #79,it's not actually using `Mmap.mmap` and perhaps should be renamed. What about `empty_tiff`?

Alternatively, you can use (warning: untested)

```julia
img = open(filename, "w") do io
    Mmap.mmap(io, Gray{N0f16}, sz3)
end
for i = 1:n
    img[:,:,i] = create_slice_data(i, sz2)   # this will write to the file
end
```

This should work at least on Linux despite apparently closing the file before values are assigned; Linux will defer the close until `img` gets garbage-collected. I am not sure about other platforms.

Of course, that doesn't create a TIFF. You'd need to do some work to write the header and set up empty chunks for the slice planes, essentially as `MmappedTIFF` does in #79. Basically, you mmap the entire file-buffer and then assign slices to correctly-placed `view`s within the full buffer. Of course, if it's possible to pack all slice planes densely, then just a single `view` will suffice for an entire 3d array.

This may be more of a pain than any benefit you'd derive from it, so just renaming `memmap` seems expeditious.

**Comment by timholy** [comment]
I'd be fine with either of those names.

`push!` support to `MmappedTIFF` would be possible but it seems likely to have constraints: I think that once the file is mmapped its size is fixed. I'm not entirely sure, though.

So `push!` could work, but we'd have to keep track of the "existing size"

**Comment by tlnagy** [comment]
Actually, the better solution is likely something like

```julia
img = empty(LazyTIFF, T, "filepath.tif")
```

where `LazyTIFF` is `DiskTaggedImage` renamed. I think that would be a more Julian approach.

What do you think?

**Comment by timholy** [comment]
That works for me!

**Comment by tlnagy** [comment]
Throwing the `memmap` deprecation and introducing the new `empty` syntax should probably happen before I tag v0.6.0 for release and then `memmap` can be removed in v0.7.0
