### ISSUE TITLE
incompatible Float64 encoding?

### ISSUE THREAD

**Issue by johnnychen94** [tlnagy/TiffImages.jl#84]
This is only an issue of `Float64` and not `N0f8`.

```julia
using ImageCore, TiffImages
img = rand(RGB{Float64}, 64, 64)
TiffImages.save("tmp.tif", img)
img_loadback = TiffImages.load("tmp.tif")

img == img_loadback # true
```

However, this "tmp.tif" file is not loadable by other image viewers (both macOS and Windows' default image viewer fail to open it).

<img width="252" alt="image" src="https://user-images.githubusercontent.com/8684355/181216995-c74f7774-8db1-4f05-a137-9db9423e71ce.png">

**Comment by tlnagy** [comment]
Can those default image viewers open 64bit floating bit RGBs normally? AFAIK, support for opening those is pretty limited to scientific TIFF readers, i.e. Fiji/ImageJ or Napari.

For example Fiji is capable of opening them with the BioFormats plugin:

![image](https://user-images.githubusercontent.com/1661487/181344830-22df0adf-f4e0-4740-a4d5-1bfca76e73b0.png)

And Napari as well:

![image](https://user-images.githubusercontent.com/1661487/181345129-8115ebc0-f42c-4789-9d42-3910a5bfbbad.png)

**Comment by johnnychen94** [comment]
I see. So this is because our TiffImages format is too advanced?

**Comment by tlnagy** [comment]
Yeah, unfortunately simple TIFF readers are quite limited in what datatypes they support. TiffImages.jl supports reading/writing many combinations that are valid TIFFs but other less flexible readers might not support. 

That said, I don't support all TIFFs either, but I try to support most common scientific TIFF types.

**Comment by johnnychen94** [comment]
Curiously, if we wrap the LibTIFF C library, would you like to maintain it as a fallback backend in TiffImages for cases we don't have much time/priority to implement?

**Comment by tlnagy** [comment]
I simply don't have the bandwidth to wrap it or really maintain this year. This package serves my needs for processing my microscopy images (particularly with it's advanced mmapping facilities that LibTIFF doesn't have AFAIK). 

I haven't gotten too many complaints since ImageIO.jl switched to using TiffImages.jl. Has it been causing problems for you?

**Comment by johnnychen94** [comment]
Not much for the main functionality stuff. The Jpeg compression stuff comes from the recent GSoC project https://github.com/ashwani-rathee/ExifViewer.jl/issues/5 where thumbnail is a TIFF bytes sequence with JPEG compression.

FYI, I'm working part-time in [tongyuan.cc](https://github.com/Suzhou-Tongyuan) to bring a compatible image processing toolbox to MATLAB and I sometimes find compatibility issues across implementations for edge cases and advanced keyword options.
