### ISSUE TITLE
comapt version of `PkgVersion` is old

### ISSUE THREAD

**Issue by vancleve** [tlnagy/TiffImages.jl#86]
https://github.com/tlnagy/TiffImages.jl/blob/c9f5e4d3ece0fe091c830d9b92a0a75fbfce7ed8/Project.toml#L29

PkgVersion is now at 0.3.2

**Comment by tlnagy** [comment]
Looks like that package has seen a flurry of development recently. Thanks for letting me know. I'll merge #87 into the TiffImages v0.6.1 release.
