### ISSUE TITLE
Trigger patch release

### ISSUE THREAD

**Issue by juliohm** [tlnagy/TiffImages.jl#94]
The version was already bumped in the Project.toml, but the release wasn't triggered.

**Comment by tlnagy** [comment]
Thanks for letting me know. I guess I was waiting to release it since it seemed so minor and was waiting if anything else might be worth bundling into this patch release. What's convention to do in that case?

**Comment by tlnagy** [comment]
Fixed by https://github.com/tlnagy/TiffImages.jl/commit/82f2ec42675404d06cf2b39057b6809256b93cf1
