### ISSUE TITLE
Ability to load extremely large tiff stacks?

### ISSUE THREAD

**Issue by ajsc4** [tlnagy/TiffImages.jl#95]
Currently, attempting to load a tiff stack over ~50gb in size results in only the first slice being loaded. Is there anyway to ensure the whole thing is loaded?

**Comment by tlnagy** [comment]
Sorry for the delay with getting back to you, but can you provide any information about the TIFF? For example, could you run:

```julia
julia> using TiffImages

julia> img = TiffImages.load("tmp.tiff"); # replace the string with your file's path

julia> size(img)
(512, 512)

julia> img.ifds[1]
IFD, with tags: 
	Tag(IMAGEWIDTH, 512)
	...
	Tag(SAMPLEFORMAT, 1)
```
And paste the output in this issue?

`TiffImages.jl` should be able to handle big TIFFs (>4GB) just fine.
